### ISSUE TITLE
Default parsing logic to zones first

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/legato#39]
Favor visualizing zones over tabs if both are present in an article.

**Comment by ggailey777** [comment]
Until support is available for both, you could also have a setting that lets you toggle this behavior.

**Comment by craigshoemaker** [comment]
addressed by ccf3cf76148b1536731956217e0eea98d4573a69

**Comment by craigshoemaker** [comment]
Closing this for now. We can create a new issue for a toggle if we decide to go that route.

cc: @johnpapa
