### ISSUE TITLE
Support tabs and zone pivots

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/legato#40]
Some articles feature tabs and zone pivot areas in the same article.

How should we handle this situation?

There are a at least few options (and very likely more):

1. **Toggle**: Allow the user to toggle between the different visualizations (zones or tabs). This could create an interesting experience which allows the editor to stay clean and lets you focus on one area at at time.

2. **Layered gutters**: Show multiple colored lined and delimiters in the gutter to represent the nested nature of areas.

Would love feedback from @johnpapa, @kgremban, and @ggailey777 on these options and perhaps other approaches.

**Comment by ggailey777** [comment]
Just a point of clarification. Tabs can be nested inside zone pivots, but a tab can never contain a zone pivot. I can see a case where the outside colored bracket (solid) is ZP and an inner colored bracket (dashed?) is a tab.

We might want to implement the toggle option until a more complete solution is created.

**Comment by craigshoemaker** [comment]
Closing this issue in preparation for repo archival. If you want to continue to track this work, please create an issue in the [vscode-docs-authoring](https://github.com/microsoft/vscode-docs-authoring) repo.
