### ISSUE TITLE
Collapsable tab/pivot areas (aka regions)

### ISSUE THREAD

**Issue by ggailey777** [craigshoemaker/legato#41]
It would be super-cool if there was a way to double-click and collapse specific tabs/pivots throughout the doc. This would let you hide tab/pivot content other than the ones you are working on.

**Comment by craigshoemaker** [comment]
Would probably have to override default collapsing features provided by VS Code for Markdown files.

Is it preferable to have the areas collapsible rather than the different aspects of Markdown?

**Comment by craigshoemaker** [comment]
Closing this issue in preparation for repo archival. If you want to continue to track this work, please create an issue in the [vscode-docs-authoring](https://github.com/microsoft/vscode-docs-authoring) repo.
