### ISSUE TITLE
Extension seems to suppress Enter keystrokes

### ISSUE THREAD

**Issue by ggailey777** [craigshoemaker/legato#43]
OK, this is a weird one:

1. While running the extension, at some point VS Code stopped responding to the Enter key.
2. I restarted VS Code and it still didn't respond.
3. Disabled the extension (which required a restart)
4. Enter key now works.
5. Reenabled extension.
6. Enter key no longer works again 😦

**Comment by craigshoemaker** [comment]
Not convinced this is specific to the extension. I have seen this same behavior in VS Code without the extension. The virtue of the fact that you reloaded the window (to disable the extension) may have been the actual remedy.

**Comment by craigshoemaker** [comment]
Closing this issue in preparation for repo archival. If you want to continue to track this work, please create an issue in the [vscode-docs-authoring](https://github.com/microsoft/vscode-docs-authoring) repo.
