### ISSUE TITLE
Keep area colors consistent

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/legato#44]
It’s a little off putting to have sections with the same label that are not colored consistently. Would be nice to ensure that article that have multiple tabs or zones style areas with consistent gutter colors.

**Comment by johnpapa** [comment]
Can you explain what that means? Perhaps show an example of what is happening and what you expect.

**Comment by craigshoemaker** [comment]
Notice how tabs that have the same labels have different color gutters:

![image](https://user-images.githubusercontent.com/127797/121540974-e3fa1800-c9d4-11eb-8051-c5e06a7460e0.png)

**Comment by craigshoemaker** [comment]
Closing this issue in preparation for repo archival. If you want to continue to track this work, please create an issue in the [vscode-docs-authoring](https://github.com/microsoft/vscode-docs-authoring) repo.
