### ISSUE TITLE
Handle monikers

### ISSUE THREAD

**Issue by garyericson** [craigshoemaker/legato#46]
Monikers are essentially conditional content markers that are very similar to zone pivots. They're described for Azure content in the Contributor Guide here: [Azure DevOps versioning and moniker guidance](https://review.docs.microsoft.com/en-us/help/contribute/azure-devops-versioning-monikers?branch=master).

Zones are formatted like this:
```
::: zone pivot="<pivot-id>"
<content>
::: zone-end
```

Monikers are formatted like this:
```
::: moniker range="<moniker values>"
<content>
::: moniker-end
```

For example:
```
::: moniker range=">=sql-server-ver15||>=sql-server-linux-ver15"
In part four of this four-part tutorial series, you'll deploy a linear regression model developed in Python into a SQL Server database using Machine Learning Services or Big Data Clusters.
::: moniker-end
::: moniker range="=sql-server-2017"
In part four of this four-part tutorial series, you'll deploy a linear regression model developed in Python into a SQL Server database using Machine Learning Services.
::: moniker-end
```

Moniker values are set by the user with a Version dropdown box above the TOC. In this example, if the user selected SQL Server 2017, then only the second version of this sentence would appear.

**Comment by craigshoemaker** [comment]
Thanks, @garyericson!

Is this expression `>=sql-server-ver15||>=sql-server-linux-ver15` interpreted as:

> Show the enclosed content when the current version is set to a value greater than or equal to `sql-server-ver15` OR greater than or equal to `sql-server-linux-ver15`

?

**Comment by garyericson** [comment]
Yes, that's correct.

**Comment by craigshoemaker** [comment]
Closing this issue in preparation for repo archival. This extension is now a part of the Docs Authoring Pack. If you want to continue to track this work, please create an issue in the [vscode-docs-authoring](https://github.com/microsoft/vscode-docs-authoring) repo.
