### ISSUE TITLE
Unresponsive error

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/legato#47]
from @JasonWHowell 

The extension seems to hang for a while when I open azure-docs-pr. Does it try to run across all files or something?

Behavior is present on file: `articles\data-factory\control-flow-expression-language-functions.md`
    

## Error
Here's the associated error message.

```
[renderer1] [warning] UNRESPONSIVE extension host, 'craig-shoemaker.vscode-docs-visual-areas' took 97% 
of 5166.207ms, saved PROFILE here: 'file:///c%3A/Users/jasonh/AppData/Local/Temp/exthost-e205a4.cpuprofile' 
[{​​​​​​"id":"craig-shoemaker.vscode-docs-visual-areas","total":5001946,"percentage":97}​​​​​​,{​​​​​​ id":"program",
"total":163942,"percentage":3}​​​​​​]

[renderer1] [warning] UNRESPONSIVE extension host, 'craig-shoemaker.vscode-docs-visual-areas' took 98%
 of 5134.953ms, saved PROFILE here: 'file:///c%3A/Users/jasonh/AppData/Local/Temp/exthost-c928b6.cpuprofile' 
[{​​​​​​"id":"craig-shoemaker.vscode-docs-visual-areas","total":5007023,"percentage":98}​​​​​​,{​​​​​​ id":"program",
"total":127571,"percentage":2}​​​​​​]
```

**Comment by JasonWHowell** [comment]
The repo file is in azure-docs-pr 
https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/data-factory/control-flow-expression-language-functions.md

**Comment by craigshoemaker** [comment]
Closing this issue in preparation for repo archival. This extension is now a part of the Docs Authoring Pack. If you want to continue to track this work, please create an issue in the [vscode-docs-authoring](https://github.com/microsoft/vscode-docs-authoring) repo.
