### ISSUE TITLE
parser: tabs

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/legato#5]
Examine an article that uses zone pivots and determine which line numbers are inside a tabbed section.

Approaches may vary, but we may want to have the parser publish an event that can signal to the part of the extension that updates the UI an event argument similar to the following:

```
[{
  type: "tab",
  label: "C#",
  startLine: 45,
  endLine: 123,
},
{
  type: "tab",
  label: "JavaScript",
  startLine: 124,
  endLine: 211,
}]
```

**Comment by johnpapa** [comment]
doesnt need to be an event, but events will call the function that looks at the array

**Comment by craigshoemaker** [comment]
we are able to accomplish what we need via regex patterns so an explicit parser is not necessary.
