### ISSUE TITLE
colorizor

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/legato#6]
A module that accepts boundary info to help users visualize the content different sections.

## Possible approaches

- [Bracket Pair Colorizer extension](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2)
- Gutter icons

## Example boundary info

```
[{
  type: "zone",
  label: "C#",
  startLine: 45,
  endLine: 123,
},
{
  type: "zone",
  label: "JavaScript",
  startLine: 124,
  endLine: 211,
}]
```

## Resources

- [decorator-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/decorator-sample)
- [gutterIconPath](https://github.com/microsoft/vscode/issues/5923)
- [setDecorations](https://code.visualstudio.com/api/references/vscode-api#TextEditor)
- [Range](https://code.visualstudio.com/api/references/vscode-api#Range)
- [DecorationOptions](https://code.visualstudio.com/api/references/vscode-api#DecorationOptions)

**Comment by johnpapa** [comment]
Closing as we have the `Areas` interface which stores this info
